"""SQLAlchemy declarative base and shared column mixins.

WHAT: `Base` is the parent of every ORM model. `TimestampMixin` and
`UUIDPrimaryKeyMixin` provide the columns nearly every table needs.

WHY a naming convention: Alembic autogenerate produces much cleaner, stable
migration diffs when indexes/constraints have deterministic names. Without this,
Postgres auto-names constraints and every migration churns.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Deterministic names for every constraint type. `%(column_0_label)s` etc. are
# Alembic/SQLAlchemy tokens.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base shared by all models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKeyMixin:
    """A `uuid` primary key generated by the application.

    WHY app-side UUIDs (not bigserial): job ingestion and dedupe need a stable id
    before the row is flushed, ids are safe to expose in URLs without leaking row
    counts, and merging data across environments never collides.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )


class TimestampMixin:
    """`created_at` / `updated_at`, both server-managed UTC timestamps.

    `updated_at` uses `onupdate` so any ORM update refreshes it without callers
    remembering to. Server defaults mean rows inserted by migrations/seeds also
    get correct values.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
