"""initial schema

Creates every table in the v1 data model (see ARCHITECTURE.md section 3) plus
the two Postgres extensions it depends on:

    citext   — case-insensitive email column on `users`
    pg_trgm  — trigram indexes for company/location typeahead (added later, but
               the extension is provisioned here so those migrations are pure
               index adds)

The autogenerated table DDL below is left as Alembic produced it; the only
hand-edits are the CREATE EXTENSION statements at the top of upgrade().

Revision ID: 0001
Revises:
Create Date: 2026-09-10 08:28:09.710211+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Extensions first — the `users.email` CITEXT column below needs `citext`.
    # IF NOT EXISTS makes this safe on databases where a superuser pre-created
    # them (e.g. some managed Postgres setups).
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "page_view",
                "search",
                "job_view",
                "apply_click",
                "filter_apply",
                "seeker_signup",
                "employer_signup",
                "job_post",
                "saved_job",
                "saved_search",
                name="analytics_event_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("session_id", sa.String(length=64), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column(
            "properties",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analytics_events")),
    )
    op.create_index("ix_analytics_events_job_id", "analytics_events", ["job_id"], unique=False)
    op.create_index(
        "ix_analytics_events_source_id", "analytics_events", ["source_id"], unique=False
    )
    op.create_index(
        "ix_analytics_events_type_occurred",
        "analytics_events",
        ["event_type", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index("ix_audit_log_actor", "audit_log", ["actor_user_id"], unique=False)
    op.create_index("ix_audit_log_created_at", "audit_log", ["created_at"], unique=False)
    op.create_index("ix_audit_log_entity", "audit_log", ["entity_type", "entity_id"], unique=False)
    op.create_table(
        "companies",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("match_key", sa.String(length=255), nullable=False),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
        sa.UniqueConstraint("match_key", name=op.f("uq_companies_match_key")),
        sa.UniqueConstraint("slug", name=op.f("uq_companies_slug")),
    )
    op.create_table(
        "fields",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("icon", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fields")),
        sa.UniqueConstraint("slug", name=op.f("uq_fields_slug")),
    )
    op.create_table(
        "sources",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("adapter", sa.String(length=64), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "aggregator", "ats", "scraper", name="source_kind", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "tier",
            sa.Enum("free", "paid", name="source_tier", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("base_url", sa.Text(), nullable=True),
        sa.Column(
            "config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("requires_api_key", sa.Boolean(), nullable=False),
        sa.Column("api_key_ref", sa.String(length=64), nullable=True),
        sa.Column("rate_limit_per_min", sa.Integer(), nullable=True),
        sa.Column("request_timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("refresh_interval_minutes", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("key", name=op.f("uq_sources_key")),
    )
    op.create_table(
        "users",
        sa.Column(
            "role",
            sa.Enum("seeker", "employer", "admin", name="user_role", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_email_verified", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "admin_profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "admin_role",
            sa.Enum(
                "superadmin",
                "moderator",
                "editor",
                "analyst",
                name="admin_role",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_admin_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_admin_profiles")),
    )
    op.create_table(
        "announcements",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "info",
                "warning",
                "success",
                name="announcement_level",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_announcements_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_announcements")),
    )
    op.create_table(
        "employer_profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("job_title", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column(
            "account_status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                "suspended",
                name="employer_account_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("approved_by_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("plan", sa.String(length=50), nullable=True),
        sa.Column("plan_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("posting_quota", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_id"],
            ["users.id"],
            name=op.f("fk_employer_profiles_approved_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_employer_profiles_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_employer_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_employer_profiles")),
    )
    op.create_index(
        op.f("ix_employer_profiles_account_status"),
        "employer_profiles",
        ["account_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employer_profiles_company_id"), "employer_profiles", ["company_id"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "saved_searches",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "query_params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("alert_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "alert_frequency",
            sa.Enum("daily", "weekly", name="alert_frequency", native_enum=False, length=32),
            nullable=True,
        ),
        sa.Column("last_alerted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("alert_high_water_mark", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_saved_searches_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_searches")),
    )
    op.create_index(op.f("ix_saved_searches_user_id"), "saved_searches", ["user_id"], unique=False)
    op.create_table(
        "site_content",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_site_content_updated_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_content")),
        sa.UniqueConstraint("key", name=op.f("uq_site_content_key")),
    )
    op.create_table(
        "source_runs",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "success",
                "partial",
                "failed",
                name="source_run_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("jobs_seen", sa.Integer(), nullable=False),
        sa.Column("jobs_created", sa.Integer(), nullable=False),
        sa.Column("jobs_updated", sa.Integer(), nullable=False),
        sa.Column("jobs_expired", sa.Integer(), nullable=False),
        sa.Column("jobs_failed", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("log", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_source_runs_source_id_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_runs")),
        sa.UniqueConstraint("source_id", "started_at", name="uq_source_runs_source_id_started_at"),
    )
    op.create_index(op.f("ix_source_runs_source_id"), "source_runs", ["source_id"], unique=False)
    op.create_table(
        "subfields",
        sa.Column("field_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("keywords", postgresql.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["field_id"],
            ["fields.id"],
            name=op.f("fk_subfields_field_id_fields"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subfields")),
        sa.UniqueConstraint("field_id", "slug", name="uq_subfields_field_id_slug"),
    )
    op.create_index(op.f("ix_subfields_field_id"), "subfields", ["field_id"], unique=False)
    op.create_table(
        "alert_deliveries",
        sa.Column("saved_search_id", sa.UUID(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("job_count", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "sent",
                "skipped",
                "failed",
                name="alert_delivery_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["saved_search_id"],
            ["saved_searches.id"],
            name=op.f("fk_alert_deliveries_saved_search_id_saved_searches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_deliveries")),
    )
    op.create_index(
        op.f("ix_alert_deliveries_saved_search_id"),
        "alert_deliveries",
        ["saved_search_id"],
        unique=False,
    )
    op.create_table(
        "jobs",
        sa.Column(
            "origin",
            sa.Enum("aggregated", "employer", name="job_origin", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("posted_by_user_id", sa.UUID(), nullable=True),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("apply_url", sa.Text(), nullable=True),
        sa.Column("apply_email", sa.String(length=320), nullable=True),
        sa.Column("apply_instructions", sa.Text(), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description_html", sa.Text(), nullable=False),
        sa.Column("description_text", sa.Text(), nullable=False),
        sa.Column("company_name_raw", sa.String(length=255), nullable=False),
        sa.Column("location_raw", sa.String(length=500), nullable=True),
        sa.Column("city", sa.String(length=200), nullable=True),
        sa.Column("region", sa.String(length=200), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("country_name", sa.String(length=100), nullable=True),
        sa.Column("is_remote", sa.Boolean(), nullable=False),
        sa.Column(
            "workplace_type",
            sa.Enum(
                "remote",
                "hybrid",
                "onsite",
                "unknown",
                name="workplace_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("remote_scope", sa.String(length=200), nullable=True),
        sa.Column("salary_min", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("salary_max", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("salary_currency", sa.String(length=3), nullable=True),
        sa.Column(
            "salary_period",
            sa.Enum(
                "year",
                "month",
                "week",
                "day",
                "hour",
                name="salary_period",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("salary_is_disclosed", sa.Boolean(), nullable=False),
        sa.Column(
            "job_type",
            sa.Enum(
                "full_time",
                "part_time",
                "contract",
                "internship",
                "temporary",
                "other",
                "unknown",
                name="job_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "experience_level",
            sa.Enum(
                "entry",
                "mid",
                "senior",
                "lead",
                "unknown",
                name="experience_level",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("field_id", sa.UUID(), nullable=True),
        sa.Column("subfield_id", sa.UUID(), nullable=True),
        sa.Column(
            "categorization_method",
            sa.Enum(
                "keyword",
                "employer",
                "admin",
                "none",
                name="categorization_method",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("categorization_confidence", sa.Float(), nullable=True),
        sa.Column("is_uncategorized", sa.Boolean(), nullable=False),
        sa.Column("visa_sponsorship", sa.Boolean(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "pending",
                "rejected",
                "closed",
                "expired",
                "hidden",
                name="job_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "moderation_status",
            sa.Enum(
                "not_required",
                "pending",
                "approved",
                "rejected",
                name="moderation_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dedupe_hash", sa.String(length=40), nullable=True),
        sa.Column("canonical_job_id", sa.UUID(), nullable=True),
        sa.Column("is_canonical", sa.Boolean(), nullable=False),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "setweight(to_tsvector('english', coalesce(title, '')), 'A') || setweight(to_tsvector('english', coalesce(company_name_raw, '')), 'B') || setweight(to_tsvector('english', coalesce(location_raw, '')), 'C') || setweight(to_tsvector('english', coalesce(description_text, '')), 'D')",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("apply_click_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(origin = 'aggregated' AND source_id IS NOT NULL AND posted_by_user_id IS NULL) OR (origin = 'employer' AND source_id IS NULL AND posted_by_user_id IS NOT NULL)",
            name=op.f("ck_jobs_origin_consistency"),
        ),
        sa.ForeignKeyConstraint(
            ["canonical_job_id"],
            ["jobs.id"],
            name=op.f("fk_jobs_canonical_job_id_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_jobs_company_id_companies"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["field_id"], ["fields.id"], name=op.f("fk_jobs_field_id_fields"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["posted_by_user_id"],
            ["users.id"],
            name=op.f("fk_jobs_posted_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_jobs_source_id_sources"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subfield_id"],
            ["subfields.id"],
            name=op.f("fk_jobs_subfield_id_subfields"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("source_id", "external_id", name="uq_jobs_source_id_external_id"),
    )
    op.create_index("ix_jobs_canonical_job_id", "jobs", ["canonical_job_id"], unique=False)
    op.create_index("ix_jobs_company_id", "jobs", ["company_id"], unique=False)
    op.create_index("ix_jobs_country_code", "jobs", ["country_code"], unique=False)
    op.create_index("ix_jobs_dedupe_hash", "jobs", ["dedupe_hash"], unique=False)
    op.create_index("ix_jobs_experience_level", "jobs", ["experience_level"], unique=False)
    op.create_index("ix_jobs_field_id", "jobs", ["field_id"], unique=False)
    op.create_index("ix_jobs_job_type", "jobs", ["job_type"], unique=False)
    op.create_index("ix_jobs_origin", "jobs", ["origin"], unique=False)
    op.create_index(
        "ix_jobs_search_vector", "jobs", ["search_vector"], unique=False, postgresql_using="gin"
    )
    op.create_index("ix_jobs_status_posted_at", "jobs", ["status", "posted_at"], unique=False)
    op.create_index("ix_jobs_subfield_id", "jobs", ["subfield_id"], unique=False)
    op.create_index(
        "ix_jobs_uncategorized",
        "jobs",
        ["is_uncategorized"],
        unique=False,
        postgresql_where="is_uncategorized",
    )
    op.create_index("ix_jobs_workplace_type", "jobs", ["workplace_type"], unique=False)
    op.create_table(
        "saved_jobs",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_saved_jobs_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_saved_jobs_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_jobs")),
        sa.UniqueConstraint("user_id", "job_id", name="uq_saved_jobs_user_id_job_id"),
    )
    op.create_index(op.f("ix_saved_jobs_job_id"), "saved_jobs", ["job_id"], unique=False)
    op.create_index(op.f("ix_saved_jobs_user_id"), "saved_jobs", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_saved_jobs_user_id"), table_name="saved_jobs")
    op.drop_index(op.f("ix_saved_jobs_job_id"), table_name="saved_jobs")
    op.drop_table("saved_jobs")
    op.drop_index("ix_jobs_workplace_type", table_name="jobs")
    op.drop_index("ix_jobs_uncategorized", table_name="jobs", postgresql_where="is_uncategorized")
    op.drop_index("ix_jobs_subfield_id", table_name="jobs")
    op.drop_index("ix_jobs_status_posted_at", table_name="jobs")
    op.drop_index("ix_jobs_search_vector", table_name="jobs", postgresql_using="gin")
    op.drop_index("ix_jobs_origin", table_name="jobs")
    op.drop_index("ix_jobs_job_type", table_name="jobs")
    op.drop_index("ix_jobs_field_id", table_name="jobs")
    op.drop_index("ix_jobs_experience_level", table_name="jobs")
    op.drop_index("ix_jobs_dedupe_hash", table_name="jobs")
    op.drop_index("ix_jobs_country_code", table_name="jobs")
    op.drop_index("ix_jobs_company_id", table_name="jobs")
    op.drop_index("ix_jobs_canonical_job_id", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_alert_deliveries_saved_search_id"), table_name="alert_deliveries")
    op.drop_table("alert_deliveries")
    op.drop_index(op.f("ix_subfields_field_id"), table_name="subfields")
    op.drop_table("subfields")
    op.drop_index(op.f("ix_source_runs_source_id"), table_name="source_runs")
    op.drop_table("source_runs")
    op.drop_table("site_content")
    op.drop_index(op.f("ix_saved_searches_user_id"), table_name="saved_searches")
    op.drop_table("saved_searches")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_employer_profiles_company_id"), table_name="employer_profiles")
    op.drop_index(op.f("ix_employer_profiles_account_status"), table_name="employer_profiles")
    op.drop_table("employer_profiles")
    op.drop_table("announcements")
    op.drop_table("admin_profiles")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_table("users")
    op.drop_table("sources")
    op.drop_table("fields")
    op.drop_table("companies")
    op.drop_index("ix_audit_log_entity", table_name="audit_log")
    op.drop_index("ix_audit_log_created_at", table_name="audit_log")
    op.drop_index("ix_audit_log_actor", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index("ix_analytics_events_type_occurred", table_name="analytics_events")
    op.drop_index("ix_analytics_events_source_id", table_name="analytics_events")
    op.drop_index("ix_analytics_events_job_id", table_name="analytics_events")
    op.drop_table("analytics_events")
    # ### end Alembic commands ###
