"""Seed data for the categorization taxonomy (`fields` + `subfields`).

This is the STARTING taxonomy. Everything here is editable in the admin panel —
fields and sub-fields can be renamed, reordered, deactivated, added, or merged
without touching code. The `keywords` lists are the classifier's training data:
when a non-technical admin sees a mis-categorized job, the fix is editing a
keyword list here (or in the admin UI), not a code change.

Structure: `TAXONOMY` is an ordered list of fields; each field has an ordered
list of sub-fields; each sub-field has a keyword list used by
`app/categorization/classifier.py`.

Keyword guidance:
    * lowercase; matched case-insensitively as whole words / short phrases,
    * favour terms that appear in a job *title* (weighted heavily) — e.g.
      "react", "registered nurse", "line cook",
    * a few disambiguating description terms are fine, but avoid generic words
      ("manager", "senior") that appear across every field.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class SeedSubfield:
    slug: str
    name: str
    keywords: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class SeedField:
    slug: str
    name: str
    description: str
    icon: str
    subfields: list[SeedSubfield] = field(default_factory=list)


# ---------------------------------------------------------------------------
# The taxonomy. Order here is the display order.
# ---------------------------------------------------------------------------
TAXONOMY: list[SeedField] = [
    SeedField(
        slug="computing-tech",
        name="Computing & Tech",
        description="Software, data, infrastructure, security and IT roles.",
        icon="cpu",
        subfields=[
            SeedSubfield(
                "software-engineering",
                "Software Engineering",
                [
                    "software engineer",
                    "backend",
                    "back-end",
                    "full stack",
                    "full-stack",
                    "golang",
                    "java developer",
                    "c++",
                    "rust",
                    "python developer",
                    "api",
                    "microservices",
                    "programmer",
                    "sde",
                ],
            ),
            SeedSubfield(
                "web-development",
                "Web Development",
                [
                    "frontend",
                    "front-end",
                    "react",
                    "vue",
                    "angular",
                    "javascript",
                    "typescript",
                    "web developer",
                    "next.js",
                    "svelte",
                    "css",
                    "html",
                    "webflow",
                    "wordpress",
                ],
            ),
            SeedSubfield(
                "mobile-development",
                "Mobile Development",
                [
                    "ios",
                    "android",
                    "swift",
                    "kotlin",
                    "react native",
                    "flutter",
                    "mobile developer",
                    "objective-c",
                    "xcode",
                    "jetpack compose",
                ],
            ),
            SeedSubfield(
                "data-science",
                "Data Science & Analytics",
                [
                    "data scientist",
                    "data analyst",
                    "analytics",
                    "sql",
                    "tableau",
                    "power bi",
                    "pandas",
                    "r language",
                    "statistician",
                    "bi analyst",
                    "looker",
                    "data engineer",
                    "etl",
                    "dbt",
                ],
            ),
            SeedSubfield(
                "machine-learning-ai",
                "Machine Learning & AI",
                [
                    "machine learning",
                    "ml engineer",
                    "deep learning",
                    "nlp",
                    "llm",
                    "computer vision",
                    "pytorch",
                    "tensorflow",
                    "ai engineer",
                    "mlops",
                    "generative ai",
                    "research scientist",
                ],
            ),
            SeedSubfield(
                "devops",
                "DevOps & SRE",
                [
                    "devops",
                    "site reliability",
                    "sre",
                    "kubernetes",
                    "docker",
                    "terraform",
                    "ci/cd",
                    "aws",
                    "gcp",
                    "azure",
                    "platform engineer",
                    "infrastructure engineer",
                    "ansible",
                    "observability",
                ],
            ),
            SeedSubfield(
                "cybersecurity",
                "Cybersecurity",
                [
                    "security engineer",
                    "cybersecurity",
                    "infosec",
                    "penetration test",
                    "pentester",
                    "soc analyst",
                    "application security",
                    "appsec",
                    "incident response",
                    "threat",
                    "vulnerability",
                    "ciso",
                    "grc",
                ],
            ),
            SeedSubfield(
                "it-support",
                "IT Support & Administration",
                [
                    "it support",
                    "help desk",
                    "helpdesk",
                    "desktop support",
                    "system administrator",
                    "sysadmin",
                    "network administrator",
                    "it technician",
                    "service desk",
                    "endpoint",
                ],
            ),
            SeedSubfield(
                "qa-testing",
                "QA & Testing",
                [
                    "qa engineer",
                    "quality assurance",
                    "test engineer",
                    "sdet",
                    "automation testing",
                    "manual testing",
                    "cypress",
                    "selenium",
                    "playwright",
                    "test automation",
                ],
            ),
            SeedSubfield(
                "product-management",
                "Product Management",
                [
                    "product manager",
                    "product owner",
                    "technical product manager",
                    "group product manager",
                    "product management",
                    "roadmap",
                    "cpo",
                ],
            ),
        ],
    ),
    SeedField(
        slug="design",
        name="Design",
        description="Product, visual, and experience design.",
        icon="palette",
        subfields=[
            SeedSubfield(
                "ui-ux",
                "UI/UX Design",
                [
                    "ux designer",
                    "ui designer",
                    "ui/ux",
                    "product designer",
                    "interaction designer",
                    "user experience",
                    "figma",
                    "wireframe",
                    "prototyping",
                    "design system",
                ],
            ),
            SeedSubfield(
                "graphic-design",
                "Graphic Design",
                [
                    "graphic designer",
                    "visual designer",
                    "brand designer",
                    "print design",
                    "adobe illustrator",
                    "photoshop",
                    "layout",
                    "packaging design",
                ],
            ),
            SeedSubfield(
                "product-design",
                "Product Design",
                [
                    "product designer",
                    "senior product designer",
                    "design lead",
                    "ux/ui",
                    "end-to-end design",
                    "user-centered",
                ],
            ),
            SeedSubfield(
                "motion-video",
                "Motion & Video",
                [
                    "motion designer",
                    "motion graphics",
                    "video editor",
                    "animator",
                    "after effects",
                    "3d artist",
                    "cinema 4d",
                    "videographer",
                ],
            ),
            SeedSubfield(
                "industrial-design",
                "Industrial & Architectural Design",
                [
                    "industrial designer",
                    "architect",
                    "cad designer",
                    "autocad",
                    "revit",
                    "interior designer",
                    "spatial designer",
                ],
            ),
        ],
    ),
    SeedField(
        slug="business",
        name="Business",
        description="Sales, marketing, finance, people, strategy and operations.",
        icon="briefcase",
        subfields=[
            SeedSubfield(
                "sales",
                "Sales",
                [
                    "sales representative",
                    "account executive",
                    "sdr",
                    "bdr",
                    "sales manager",
                    "business development",
                    "inside sales",
                    "field sales",
                    "quota",
                    "sales engineer",
                    "channel sales",
                ],
            ),
            SeedSubfield(
                "marketing",
                "Marketing",
                [
                    "marketing manager",
                    "digital marketing",
                    "growth marketing",
                    "seo",
                    "sem",
                    "content marketing",
                    "brand manager",
                    "demand generation",
                    "product marketing",
                    "email marketing",
                    "performance marketing",
                    "cmo",
                ],
            ),
            SeedSubfield(
                "finance-accounting",
                "Finance & Accounting",
                [
                    "accountant",
                    "financial analyst",
                    "controller",
                    "bookkeeper",
                    "fp&a",
                    "auditor",
                    "tax",
                    "accounts payable",
                    "accounts receivable",
                    "cfo",
                    "treasury",
                    "financial planning",
                ],
            ),
            SeedSubfield(
                "human-resources",
                "Human Resources & Recruiting",
                [
                    "human resources",
                    "hr manager",
                    "recruiter",
                    "talent acquisition",
                    "people operations",
                    "hr business partner",
                    "hrbp",
                    "compensation",
                    "benefits",
                    "onboarding",
                    "chro",
                ],
            ),
            SeedSubfield(
                "operations",
                "Operations & Strategy",
                [
                    "operations manager",
                    "business operations",
                    "chief of staff",
                    "strategy",
                    "process improvement",
                    "operations analyst",
                    "revenue operations",
                    "revops",
                    "coo",
                ],
            ),
            SeedSubfield(
                "project-management",
                "Project & Program Management",
                [
                    "project manager",
                    "program manager",
                    "scrum master",
                    "agile coach",
                    "pmo",
                    "delivery manager",
                    "pmp",
                ],
            ),
            SeedSubfield(
                "consulting",
                "Consulting",
                [
                    "consultant",
                    "management consultant",
                    "advisory",
                    "strategy consultant",
                    "implementation consultant",
                    "solutions consultant",
                ],
            ),
            SeedSubfield(
                "legal",
                "Legal & Compliance",
                [
                    "lawyer",
                    "attorney",
                    "legal counsel",
                    "paralegal",
                    "compliance officer",
                    "contract manager",
                    "general counsel",
                    "legal operations",
                    "regulatory",
                ],
            ),
        ],
    ),
    SeedField(
        slug="customer-service",
        name="Customer Service",
        description="Support, success and contact-centre roles.",
        icon="headset",
        subfields=[
            SeedSubfield(
                "customer-support",
                "Customer Support",
                [
                    "customer support",
                    "support specialist",
                    "customer service representative",
                    "help desk",
                    "support agent",
                    "customer care",
                    "csr",
                ],
            ),
            SeedSubfield(
                "customer-success",
                "Customer Success",
                [
                    "customer success manager",
                    "csm",
                    "account manager",
                    "onboarding specialist",
                    "renewals",
                    "client success",
                    "customer experience",
                ],
            ),
            SeedSubfield(
                "technical-support",
                "Technical Support",
                [
                    "technical support engineer",
                    "technical support specialist",
                    "product support",
                    "tier 2 support",
                    "escalation engineer",
                    "support engineer",
                ],
            ),
            SeedSubfield(
                "call-center",
                "Call Centre",
                [
                    "call center",
                    "call centre",
                    "contact center",
                    "inbound",
                    "outbound",
                    "telesales",
                    "collections agent",
                    "dispatcher",
                ],
            ),
        ],
    ),
    SeedField(
        slug="healthcare",
        name="Healthcare",
        description="Clinical, allied health, mental health and health administration.",
        icon="stethoscope",
        subfields=[
            SeedSubfield(
                "nursing",
                "Nursing",
                [
                    "registered nurse",
                    "nurse practitioner",
                    "rn",
                    "lpn",
                    "charge nurse",
                    "icu nurse",
                    "er nurse",
                    "nursing",
                    "cna",
                    "nurse manager",
                ],
            ),
            SeedSubfield(
                "physicians",
                "Physicians & Surgeons",
                [
                    "physician",
                    "doctor",
                    "surgeon",
                    "md ",
                    "gp ",
                    "consultant physician",
                    "hospitalist",
                    "anesthesiologist",
                    "radiologist",
                    "pediatrician",
                ],
            ),
            SeedSubfield(
                "allied-health",
                "Allied Health",
                [
                    "physical therapist",
                    "occupational therapist",
                    "pharmacist",
                    "radiographer",
                    "medical technologist",
                    "phlebotomist",
                    "dietitian",
                    "speech therapist",
                    "paramedic",
                    "dental hygienist",
                ],
            ),
            SeedSubfield(
                "mental-health",
                "Mental Health",
                [
                    "therapist",
                    "counselor",
                    "counsellor",
                    "psychologist",
                    "psychiatrist",
                    "clinical social worker",
                    "behavioral health",
                    "mental health",
                ],
            ),
            SeedSubfield(
                "healthcare-admin",
                "Healthcare Administration",
                [
                    "medical billing",
                    "medical coder",
                    "health information",
                    "practice manager",
                    "patient coordinator",
                    "medical receptionist",
                    "clinical research coordinator",
                    "healthcare administrator",
                ],
            ),
        ],
    ),
    SeedField(
        slug="education",
        name="Education",
        description="Teaching, tutoring, instructional design and academia.",
        icon="graduation-cap",
        subfields=[
            SeedSubfield(
                "teaching",
                "Teaching",
                [
                    "teacher",
                    "lecturer",
                    "professor",
                    "instructor",
                    "educator",
                    "primary teacher",
                    "secondary teacher",
                    "substitute teacher",
                    "special education",
                    "esl teacher",
                    "teaching assistant",
                ],
            ),
            SeedSubfield(
                "tutoring",
                "Tutoring & Test Prep",
                [
                    "tutor",
                    "test prep",
                    "academic coach",
                    "online tutor",
                    "learning support",
                    "sat tutor",
                ],
            ),
            SeedSubfield(
                "instructional-design",
                "Instructional Design & EdTech",
                [
                    "instructional designer",
                    "curriculum developer",
                    "learning designer",
                    "e-learning",
                    "learning experience designer",
                    "training developer",
                    "lms",
                ],
            ),
            SeedSubfield(
                "academic-research",
                "Academic Research",
                [
                    "postdoc",
                    "postdoctoral",
                    "research fellow",
                    "phd position",
                    "research associate",
                    "principal investigator",
                    "lab manager",
                ],
            ),
            SeedSubfield(
                "education-administration",
                "Education Administration",
                [
                    "principal",
                    "dean",
                    "registrar",
                    "admissions counselor",
                    "school administrator",
                    "academic advisor",
                    "provost",
                ],
            ),
        ],
    ),
    SeedField(
        slug="trades",
        name="Trades",
        description="Skilled manual trades and technicians.",
        icon="wrench",
        subfields=[
            SeedSubfield(
                "electrical",
                "Electrical",
                [
                    "electrician",
                    "electrical technician",
                    "journeyman electrician",
                    "apprentice electrician",
                    "instrumentation technician",
                    "high voltage",
                ],
            ),
            SeedSubfield(
                "plumbing-hvac",
                "Plumbing & HVAC",
                [
                    "plumber",
                    "hvac technician",
                    "pipefitter",
                    "gas engineer",
                    "refrigeration technician",
                    "heating engineer",
                    "steamfitter",
                ],
            ),
            SeedSubfield(
                "carpentry-construction-trades",
                "Carpentry & Construction Trades",
                [
                    "carpenter",
                    "joiner",
                    "framer",
                    "cabinet maker",
                    "drywall",
                    "mason",
                    "bricklayer",
                    "roofer",
                    "concrete finisher",
                ],
            ),
            SeedSubfield(
                "welding-fabrication",
                "Welding & Fabrication",
                [
                    "welder",
                    "fabricator",
                    "mig welder",
                    "tig welder",
                    "boilermaker",
                    "sheet metal worker",
                    "structural welder",
                ],
            ),
            SeedSubfield(
                "automotive",
                "Automotive & Diesel",
                [
                    "mechanic",
                    "automotive technician",
                    "diesel technician",
                    "auto body",
                    "vehicle technician",
                    "service technician",
                    "panel beater",
                ],
            ),
            SeedSubfield(
                "heavy-equipment",
                "Heavy Equipment & Machinery",
                [
                    "heavy equipment operator",
                    "crane operator",
                    "forklift operator",
                    "excavator operator",
                    "millwright",
                    "machinist",
                    "cnc operator",
                ],
            ),
        ],
    ),
    SeedField(
        slug="hospitality",
        name="Hospitality & Tourism",
        description="Food service, lodging, events and travel.",
        icon="utensils",
        subfields=[
            SeedSubfield(
                "food-service",
                "Food & Beverage Service",
                [
                    "chef",
                    "line cook",
                    "sous chef",
                    "server",
                    "waiter",
                    "waitress",
                    "bartender",
                    "barista",
                    "kitchen porter",
                    "restaurant manager",
                    "food runner",
                    "dishwasher",
                ],
            ),
            SeedSubfield(
                "hotel-lodging",
                "Hotel & Lodging",
                [
                    "front desk",
                    "receptionist hotel",
                    "housekeeping",
                    "concierge",
                    "hotel manager",
                    "guest services",
                    "night auditor",
                    "room attendant",
                ],
            ),
            SeedSubfield(
                "events-catering",
                "Events & Catering",
                [
                    "event coordinator",
                    "event manager",
                    "catering",
                    "banquet",
                    "wedding coordinator",
                    "conference services",
                    "venue manager",
                ],
            ),
            SeedSubfield(
                "travel-tourism",
                "Travel & Tourism",
                [
                    "travel agent",
                    "tour guide",
                    "flight attendant",
                    "cabin crew",
                    "cruise",
                    "reservations agent",
                    "tourism officer",
                ],
            ),
        ],
    ),
    SeedField(
        slug="writing-content",
        name="Writing & Content",
        description="Editorial, technical writing, journalism and content production.",
        icon="pen",
        subfields=[
            SeedSubfield(
                "copywriting",
                "Copywriting & Content Writing",
                [
                    "copywriter",
                    "content writer",
                    "content strategist",
                    "seo writer",
                    "blog writer",
                    "brand copywriter",
                    "ux writer",
                    "content creator",
                ],
            ),
            SeedSubfield(
                "technical-writing",
                "Technical Writing",
                [
                    "technical writer",
                    "documentation",
                    "api documentation",
                    "technical author",
                    "content designer",
                    "knowledge base",
                ],
            ),
            SeedSubfield(
                "editing-proofreading",
                "Editing & Proofreading",
                [
                    "editor",
                    "copy editor",
                    "proofreader",
                    "managing editor",
                    "editorial assistant",
                    "subeditor",
                ],
            ),
            SeedSubfield(
                "journalism",
                "Journalism",
                [
                    "journalist",
                    "reporter",
                    "news writer",
                    "correspondent",
                    "staff writer",
                    "investigative",
                    "columnist",
                ],
            ),
        ],
    ),
    SeedField(
        slug="media-communications",
        name="Media & Communications",
        description="PR, social media, broadcast and creative production.",
        icon="megaphone",
        subfields=[
            SeedSubfield(
                "public-relations",
                "Public Relations",
                [
                    "public relations",
                    "pr manager",
                    "communications manager",
                    "media relations",
                    "press officer",
                    "corporate communications",
                ],
            ),
            SeedSubfield(
                "social-media",
                "Social Media",
                [
                    "social media manager",
                    "community manager",
                    "social media coordinator",
                    "influencer",
                    "content moderator",
                    "social strategist",
                ],
            ),
            SeedSubfield(
                "broadcast-production",
                "Broadcast & Production",
                [
                    "producer",
                    "camera operator",
                    "sound engineer",
                    "broadcast",
                    "podcast producer",
                    "audio engineer",
                    "production assistant",
                ],
            ),
            SeedSubfield(
                "photography",
                "Photography",
                ["photographer", "photo editor", "retoucher", "studio photographer"],
            ),
        ],
    ),
    SeedField(
        slug="manufacturing-logistics",
        name="Manufacturing & Logistics",
        description="Production, warehousing, supply chain and transport.",
        icon="truck",
        subfields=[
            SeedSubfield(
                "warehouse-fulfillment",
                "Warehouse & Fulfilment",
                [
                    "warehouse associate",
                    "picker packer",
                    "forklift",
                    "material handler",
                    "warehouse operative",
                    "fulfillment",
                    "loader",
                    "stocker",
                ],
            ),
            SeedSubfield(
                "supply-chain-procurement",
                "Supply Chain & Procurement",
                [
                    "supply chain",
                    "procurement",
                    "buyer",
                    "purchasing manager",
                    "logistics coordinator",
                    "inventory manager",
                    "demand planner",
                    "category manager",
                ],
            ),
            SeedSubfield(
                "production-assembly",
                "Production & Assembly",
                [
                    "production operator",
                    "assembler",
                    "machine operator",
                    "line worker",
                    "production supervisor",
                    "quality inspector",
                    "manufacturing technician",
                ],
            ),
            SeedSubfield(
                "transportation-driving",
                "Transportation & Driving",
                [
                    "truck driver",
                    "cdl driver",
                    "delivery driver",
                    "courier",
                    "hgv driver",
                    "chauffeur",
                    "logistics",
                    "fleet",
                    "route driver",
                ],
            ),
        ],
    ),
    SeedField(
        slug="science-research",
        name="Science & Research",
        description="Laboratory, environmental and applied research roles.",
        icon="flask",
        subfields=[
            SeedSubfield(
                "life-sciences",
                "Life Sciences",
                [
                    "biologist",
                    "biochemist",
                    "microbiologist",
                    "geneticist",
                    "biotech",
                    "clinical trials",
                    "research scientist biology",
                    "molecular biology",
                    "bioinformatics",
                ],
            ),
            SeedSubfield(
                "physical-sciences",
                "Physical & Chemical Sciences",
                [
                    "chemist",
                    "physicist",
                    "materials scientist",
                    "analytical chemist",
                    "process chemist",
                    "spectroscopy",
                    "formulation scientist",
                ],
            ),
            SeedSubfield(
                "environmental-science",
                "Environmental Science",
                [
                    "environmental scientist",
                    "ecologist",
                    "sustainability",
                    "environmental consultant",
                    "climate",
                    "conservation",
                    "gis analyst",
                ],
            ),
            SeedSubfield(
                "lab-technician",
                "Laboratory Technician",
                [
                    "lab technician",
                    "laboratory analyst",
                    "research technician",
                    "lab assistant",
                    "quality control analyst",
                ],
            ),
        ],
    ),
    SeedField(
        slug="engineering-industrial",
        name="Engineering (Non-software)",
        description="Mechanical, electrical, civil, chemical and related engineering.",
        icon="cog",
        subfields=[
            SeedSubfield(
                "mechanical-engineering",
                "Mechanical Engineering",
                [
                    "mechanical engineer",
                    "design engineer",
                    "hvac engineer",
                    "mechanical design",
                    "solidworks",
                    "product engineer mechanical",
                ],
            ),
            SeedSubfield(
                "electrical-engineering",
                "Electrical & Electronics Engineering",
                [
                    "electrical engineer",
                    "electronics engineer",
                    "power engineer",
                    "hardware engineer",
                    "pcb design",
                    "embedded engineer",
                    "fpga",
                ],
            ),
            SeedSubfield(
                "civil-structural-engineering",
                "Civil & Structural Engineering",
                [
                    "civil engineer",
                    "structural engineer",
                    "geotechnical",
                    "transportation engineer",
                    "water engineer",
                    "site engineer",
                ],
            ),
            SeedSubfield(
                "chemical-process-engineering",
                "Chemical & Process Engineering",
                [
                    "chemical engineer",
                    "process engineer",
                    "petroleum engineer",
                    "refinery",
                    "plant engineer",
                ],
            ),
            SeedSubfield(
                "manufacturing-engineering",
                "Manufacturing & Industrial Engineering",
                [
                    "manufacturing engineer",
                    "industrial engineer",
                    "process improvement engineer",
                    "quality engineer",
                    "lean",
                    "six sigma",
                    "automation engineer",
                ],
            ),
        ],
    ),
    SeedField(
        slug="construction-real-estate",
        name="Construction & Real Estate",
        description="Building projects, estimating, surveying and property.",
        icon="hard-hat",
        subfields=[
            SeedSubfield(
                "construction-management",
                "Construction Management",
                [
                    "construction manager",
                    "site manager",
                    "project engineer construction",
                    "superintendent",
                    "foreman",
                    "general contractor",
                    "site supervisor",
                ],
            ),
            SeedSubfield(
                "estimating-quantity-surveying",
                "Estimating & Quantity Surveying",
                [
                    "estimator",
                    "quantity surveyor",
                    "cost engineer",
                    "commercial manager construction",
                    "takeoff",
                ],
            ),
            SeedSubfield(
                "surveying-inspection",
                "Surveying & Inspection",
                [
                    "land surveyor",
                    "building inspector",
                    "surveyor",
                    "clerk of works",
                    "building control",
                ],
            ),
            SeedSubfield(
                "real-estate-property",
                "Real Estate & Property Management",
                [
                    "real estate agent",
                    "property manager",
                    "leasing consultant",
                    "realtor",
                    "letting agent",
                    "facilities manager",
                    "asset manager property",
                ],
            ),
        ],
    ),
    SeedField(
        slug="public-sector-nonprofit",
        name="Public Sector & Nonprofit",
        description="Government, policy, social work and international development.",
        icon="landmark",
        subfields=[
            SeedSubfield(
                "public-policy-government",
                "Public Policy & Government",
                [
                    "policy analyst",
                    "public affairs",
                    "government relations",
                    "legislative",
                    "civil servant",
                    "program officer government",
                    "public administration",
                ],
            ),
            SeedSubfield(
                "social-work-community",
                "Social Work & Community Services",
                [
                    "social worker",
                    "case manager",
                    "community outreach",
                    "youth worker",
                    "family support worker",
                    "housing officer",
                    "support worker",
                ],
            ),
            SeedSubfield(
                "nonprofit-fundraising",
                "Nonprofit & Fundraising",
                [
                    "fundraising",
                    "development officer nonprofit",
                    "grant writer",
                    "donor relations",
                    "philanthropy",
                    "nonprofit program manager",
                    "ngo",
                ],
            ),
            SeedSubfield(
                "international-development",
                "International Development & Aid",
                [
                    "humanitarian",
                    "monitoring and evaluation",
                    "m&e officer",
                    "field coordinator",
                    "relief",
                    "development programme",
                    "unicef",
                    "usaid",
                ],
            ),
        ],
    ),
    SeedField(
        slug="agriculture-environment",
        name="Agriculture & Environment",
        description="Farming, agronomy, forestry and land management.",
        icon="sprout",
        subfields=[
            SeedSubfield(
                "farming-crop-production",
                "Farming & Crop Production",
                [
                    "farm worker",
                    "farm manager",
                    "agronomist",
                    "crop",
                    "orchard",
                    "greenhouse grower",
                    "irrigation",
                    "harvest",
                ],
            ),
            SeedSubfield(
                "livestock-animal-care",
                "Livestock & Animal Care",
                [
                    "herdsman",
                    "dairy",
                    "livestock manager",
                    "veterinary technician",
                    "animal care",
                    "poultry",
                    "ranch hand",
                ],
            ),
            SeedSubfield(
                "forestry-land-management",
                "Forestry & Land Management",
                [
                    "forester",
                    "arborist",
                    "gamekeeper",
                    "ranger",
                    "land manager",
                    "tree surgeon",
                    "conservation officer",
                ],
            ),
        ],
    ),
    SeedField(
        slug="skilled-services",
        name="Personal & Protective Services",
        description="Security, cleaning, personal care and other in-person services.",
        icon="shield",
        subfields=[
            SeedSubfield(
                "security-services",
                "Security Services",
                [
                    "security guard",
                    "security officer",
                    "loss prevention",
                    "bouncer",
                    "cctv operator",
                    "close protection",
                    "door supervisor",
                ],
            ),
            SeedSubfield(
                "cleaning-facilities",
                "Cleaning & Facilities",
                [
                    "cleaner",
                    "janitor",
                    "custodian",
                    "housekeeper",
                    "caretaker",
                    "grounds keeper",
                    "facilities operative",
                ],
            ),
            SeedSubfield(
                "personal-care",
                "Personal Care & Wellbeing",
                [
                    "caregiver",
                    "care assistant",
                    "home health aide",
                    "support worker",
                    "childcare",
                    "nanny",
                    "hairdresser",
                    "barber",
                    "beautician",
                    "massage therapist",
                    "personal trainer",
                ],
            ),
            SeedSubfield(
                "emergency-services",
                "Emergency & Protective",
                [
                    "firefighter",
                    "police officer",
                    "emt",
                    "correctional officer",
                    "lifeguard",
                    "coast guard",
                ],
            ),
        ],
    ),
]
